# file: k8s/cwvj-devsecops-demo-deploy.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-project
  labels:
    app: devsecops
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devsecops
  template:
    metadata:
      labels:
        app: devsecops
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: devsecops
      containers:
        - name: devsecops-project
          image: 383189130746.dkr.ecr.us-east-1.amazonaws.com/maven-app:15
          ports:
            - containerPort: 8080
